NDefines.NGame.START_DATE = "458.5.7"
NDefines.NGame.END_DATE = "2000.12.31"
NDefines.NGame.MAX_RANDOM_NEW_WORLD = "400.1.1"

NDefines.NDiplomacy.MAX_CLIENT_STATES = 12
NDefines.NCountry.MAX_CROWN_COLONIES = 16
NDefines.NCountry.OVERSEAS_CLIENT_STATES = 0					-- Allow overseas client states?

NDefines.NDiplomacy.LARGE_VASSAL_LIMIT = 500
NDefines.NDiplomacy.GREAT_POWER_VASSAL_LIMIT = 1250
NDefines.NCountry.SUBJECT_MAX_RANK = 2

NDefines.NCountry.MINIMUM_POLICY_TIME = 5
NDefines.NMilitary.INFANTRY_COST = 15.0
NDefines.NMilitary.CAVALRY_COST = 30.0
NDefines.NMilitary.WARSCORE_MAX_FROM_BATTLES = 0.5

NDefines.NDiplomacy.MAX_FREE_CITIES = 1
NDefines.NCountry.HRE_MAX_RANK = 2
NDefines.NCountry.HRE_MAX_RANK_ELECTOR = 3
NDefines.NDiplomacy.HRE_HERETIC_PENALTY = 0 -- -0.01

NDefines.NCountry.LIBERTY_DESIRE_DAIMYO = -10 -- 25

NDefines.NReligion.MAX_CHRISTIAN_RELIGIOUS_CENTERS = 4 -- base 3 + 1 bzn
--NDefines.NReligion.MAX_HELLERDIAN_GROUP_RELIGIOUS_CENTERS = 5
NDefines.NReligion.MAX_RELIGIOUS_CENTER_SPREAD_DISTANCE = 150.0
NDefines.NReligion.MONTHLY_CONVERSION_SPEED = 7.5
NDefines.NReligion.CONVERSION_ZEAL_DURATION = 9125

NDefines.NNationDesigner.MAX_DISTANCE_TO_OWNER_AREA = 3500
NDefines.NNationDesigner.MAX_DISCOVERED_PROVINCE_DISTANCE = 3750

NDefines.NCountry.MIN_TECH_FOR_CIRCUMNAVIGATE = 3
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_1 = 1541
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_2 = 1709
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_3 = 1453
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_4 = 1722
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_5 = 1611
NDefines.NCountry.CIRCUMNAVIGATION_PROVINCE_6 = 1595

NDefines.NMilitary.FORTRESS_COST = 0.25